name: Docker .NET CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Set up Docker Compose
        run: docker compose version

      - name: Build containers
        run: docker compose build

      - name: Run containers
        run: docker compose up -d

      - name: Push authentication image
        run: docker push hossenmurad/authentication

      - name: Push gateway image
        run: docker push hossenmurad/gateway

      - name: Push catalog image
        run: docker push hossenmurad/catalog

      - name: Wait and Test containers are running
        run: |
          sleep 5
          docker ps
          docker compose ps

      - name: Shut down containers
        if: always()
        run: docker compose down
